# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Nov  2 14:13:26 2022
# ------------------------------------------------

package:
  name: xtensor
  version: 0.24.3
source:
  fn: xtensor-0.24.3.tar.gz
  sha256: 3acde856b9fb8cf4e2a7b66726da541275d40ab9b002e618ad985ab97f08ca4f
  url: https://github.com/xtensor-stack/xtensor/archive/0.24.3.tar.gz
build:
  number: '1'
  string: h5362a0b_1
requirements:
  build:
    - cmake 3.24.3 h1537add_0
    - ucrt 10.0.22621.0 h57928b3_0
    - vs2015_runtime 14.32.31332 h1d6e394_9
    - vs2017_win-64 19.16.27033 hb90652a_9
    - vswhere 3.0.3 h57928b3_0
  host:
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 h3d8a991_9
    - vs2015_runtime 14.32.31332 h1d6e394_9
    - xtl 0.7.4 h5362a0b_0
  run:
    - vc >=14.1,<15
    - vs2015_runtime >=14.16.27033
    - xtl >=0.7,<0.8
  run_constrained:
    - xsimd >=8.0.3,<10
test:
  commands:
    - if not exist %LIBRARY_PREFIX%\include\xtensor\xarray.hpp (exit 1)
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor\xtensorConfig.cmake (exit 1)
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor\xtensorConfigVersion.cmake (exit
      1)
about:
  description: Multi dimensional arrays with broadcasting and lazy computing
  dev_url: https://github.com/xtensor-stack/xtensor
  doc_url: https://xtensor.readthedocs.io
  home: https://github.com/xtensor-stack/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The C++ tensor algebra library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - davidbrochart
    - wolfv
