# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Nov 24 11:13:52 2021
# ------------------------------------------------

package:
  name: xtl
  version: 0.7.4
source:
  fn: xtl-0.7.4.tar.gz
  sha256: 3c88be0e696b64150c4de7a70f9f09c00a335186b0b0b409771ef9f56bca7d9a
  url: https://github.com/xtensor-stack/xtl/archive/0.7.4.tar.gz
build:
  number: '0'
  string: h5362a0b_0
requirements:
  build:
    - cmake 3.21.3 h39d44d4_0
    - ucrt 10.0.20348.0 h57928b3_0
    - vs2015_runtime 14.29.30037 h902a5da_5
    - vs2017_win-64 19.16.27038 h2e3bad8_2
    - vswhere 2.8.4 h57928b3_0
  host:
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_5
    - vs2015_runtime 14.29.30037 h902a5da_5
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012
test:
  commands:
    - if not exist %LIBRARY_PREFIX%\include\xtl\xbasic_fixed_string.hpp (exit 1)
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtl\xtlConfig.cmake (exit 1)
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtl\xtlConfigVersion.cmake (exit 1)
about:
  description: Basic tools (containers, algorithms) used by other packages from the
    xtensor and xeus stacks.
  dev_url: https://github.com/xtensor-stack/xtl
  doc_url: https://xtl.readthedocs.io
  home: https://github.com/xtensor-stack/xtl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The xtensor-stack tools library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - conda-forge/xtensor
    - davidbrochart
    - wolfv
